### ISSUE TITLE
`Symbolics.jl` has no function `inject_registered_module_functions` anymore. 

### ISSUE THREAD

**Issue by benedict-96** [JuliaGNI/SymbolicNeuralNetworks.jl#10]
The function  `inject_registered_module_functions` is used in `SymbolicNeuralNetworks`, but has been removed from the `Symbolics` package. Not quite sure what does the job now (https://github.com/JuliaSymbolics/Symbolics.jl/blob/master/src/register.jl). For now we downgraded to `v5.0.0` to make the code work. We should also add @ZeyuanLee as a contributor I think^^

**Comment by michakraus** [comment]
Fixed by 08540f4.

**Comment by benedict-96** [comment]
Was solved in https://github.com/JuliaGNI/SymbolicNeuralNetworks.jl/pull/16.
